import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

interface ExportConfig {
    title: string;
    subtitle?: string;
    filename: string;
    columns: { header: string; dataKey: string }[];
    data: any[];
    userName?: string;
}

export const exportToPDF = ({ title, subtitle, filename, columns, data, userName }: ExportConfig) => {
    const doc = new jsPDF();
    const timestamp = format(new Date(), 'dd MMM yyyy HH:mm:ss');

    // Add Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(title, 14, 22);

    if (subtitle) {
        doc.setFontSize(11);
        doc.setTextColor(100, 100, 100);
        doc.text(subtitle, 14, 30);
    }

    // Create Table
    (doc as any).autoTable({
        startY: subtitle ? 35 : 28,
        head: [columns.map(col => col.header)],
        body: data.map(item => columns.map(col => item[col.dataKey])),
        theme: 'striped',
        headStyles: { fillStyle: 'fill', fillColor: [102, 126, 234], textColor: 255 },
        didDrawPage: (data: any) => {
            // Footer Metadata
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
            doc.setFontSize(9);
            doc.setTextColor(150, 150, 150);

            const footerY = pageHeight - 10;
            doc.text(`Generated On: ${timestamp}`, 14, footerY);
            if (userName) doc.text(`Generated By: ${userName}`, doc.internal.pageSize.width / 2, footerY, { align: 'center' });
            doc.text(`Page ${data.pageNumber}`, doc.internal.pageSize.width - 25, footerY);
        },
    });

    doc.save(`${filename}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export const exportToExcel = ({ filename, columns, data }: Omit<ExportConfig, 'title' | 'subtitle' | 'userName'>) => {
    // Format data for sheet
    const sheetData = data.map(item => {
        const row: any = {};
        columns.forEach(col => {
            row[col.header] = item[col.dataKey];
        });
        return row;
    });

    const worksheet = XLSX.utils.json_to_sheet(sheetData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');

    // Auto-size columns
    const colWidths = columns.map(col => ({
        wch: Math.max(col.header.length, ...data.map(item => (item[col.dataKey]?.toString() || '').length)) + 2
    }));
    worksheet['!cols'] = colWidths;

    XLSX.writeFile(workbook, `${filename}_${format(new Date(), 'yyyyMMdd')}.xlsx`);
};
